name: Cow BFF (CD)

concurrency: prod_environment 

on:
  push:
    branches:
      # Set your base branch name here
      - cicd-doc-revamp

jobs:
  deploy:
    name: "Deploy bundle and run notebook"
    environment: Prod
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Deploy bundle
        run: databricks bundle deploy --target production
      - name: Run notebook
        run: databricks bundle --target production run daily_report
