name: Cow BFF (sync Git Folder)

concurrency: prod_environment 

on:
  push:
    branches:
      # Set your base branch name here
      - cicd-doc-revamp

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "Update git folder "
    runs-on: [linux-ubuntu-latest]
    environment: Lighthouse 
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
      DATABRICKS_AUTH_TYPE: github-oidc      
    steps:
      - uses: databricks/setup-cli@main
      - name: Update git folder
        run: databricks repos update /Workspace/Production/dais-cow-bff --branch cicd-doc-revamp 
